### ISSUE TITLE
Chinese appear garbled

### ISSUE THREAD

**Issue by FeiZhaixiage** [manuGMG/beeShop#10]
I told you that the languages.ini file must be saved in UTF-16! Now it's garbled again.
_**new file_
![image](https://user-images.githubusercontent.com/42127557/101187361-39084a80-368f-11eb-85c3-904f5bbd92b6.png)

_**old fie_
![image](https://user-images.githubusercontent.com/42127557/101187501-694fe900-368f-11eb-8099-3e68e329dd32.png)

**Comment by FeiZhaixiage** [comment]
Although saving a file as UTF-16 will make it larger, it can display Chinese and Japanese correctly.

**Comment by manuGMG** [comment]
Thanks for reporting. 

The [release ZIP](https://github.com/manuGMG/beeShop/releases/tag/1.2.1) (v1.2.1) is now fixed.

**Comment by FeiZhaixiage** [comment]
sorry my bad.
