### ISSUE TITLE
Contribuir

### ISSUE THREAD

**Issue by Kelonio-hub** [manuGMG/beeShop#2]
Buenas tardes. 
He visto su proyecto de beeshop y me gustaría contribuir en él. 
Yo no soy desarrollador ni conozco las líneas de código, pero con el fin de que su proyecto llegue a más gente y vaya progresando, me gustaría contribuir en la difusión del mismo así como a nivel económico. Sé que al ser de cógido abierto el tema del dinero es un tanto delicado, pero me gustaría saber si aceptan donaciones para poder ayudarles. 
Un saludo. 

(Disculpen si esto no va aquí, pero desconozco cómo puedo enviarles un mensaje directo).

**Comment by manuGMG** [comment]
Hola Kelonio.
Aprecio muchísimo tus intenciones, pero no debo ni quiero aceptar dinero por un proyecto tan simple como este. Te invito a escribirme en Discord, **coinfl1p#1780**.
Saludos.
