### ISSUE TITLE
Would it be possible to create a sample (not real titles) db.csv?

### ISSUE THREAD

**Issue by Filo97** [manuGMG/beeShop#6]
As stated by the title. I'm unsure as to how it'd have to be made, so it'd be helpful to have something to reference as base.

**Comment by TimmSkiller** [comment]
If you look closely in the guide, you can see that the .CSV file you specify has to be made up of lines like this: `Name,URL`.

If you want a program that adds entries to an existing file (or a new one), have a look at [DBeeMaker](https://github.com/SashLilac/DBeeMaker).
